#version: '3.8'
#services:
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    environment:
#      POSTGRES_DB: orders_db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
#    ports:
#      - "5432:5432"
#    networks:
#      - my_network
#
#  order-service:
#    image: order-service
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: order-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orders_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: root
#    depends_on:
#      - postgres
#    ports:
#      - "8090:8090"
#    networks:
#      - my_network
#
#networks:
#  my_network:
version: '3.8'

services:
  order-service:
    image: order-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://cdcpzcsr:Cao4BUWxEmAN2TSUQp6dMVGyK41ykYXW@tiny.db.elephantsql.com/cdcpzcsr
      SPRING_DATASOURCE_USERNAME: cdcpzcsr
      SPRING_DATASOURCE_PASSWORD: Cao4BUWxEmAN2TSUQp6dMVGyK41ykYXW
    ports:
      - "8090:8090"
    networks:
      - my_network

networks:
  my_network:

