version: "3.7"
services:
  config-server:
    container_name: discovery-service
    image: discovery-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: unless-stopped