eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8091
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/ProductService
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


application:
  config:
    order-url: http://localhost:8090/api/v1/orders